name: Generate html
on:
  push:
    branches:
      - main
    paths:
      - "**/README.md"

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"
jobs:
  update-status-badges:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NAMADA_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.NAMADA_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.NAMADA_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Run script
        run: node .github/scripts/convert-readme-to-html.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ${{ secrets.NAMADA_BOT_GIT_COMMITTER_NAME }}
          commit_user_email: ${{ secrets.NAMADA_BOT_GIT_COMMITTER_EMAIL }}
          commit_author: ${{ secrets.NAMADA_BOT_GIT_AUTHOR_NAME }} <${{ secrets.NAMADA_BOT_GIT_AUTHOR_EMAIL }}>
          commit_message: "docs: generate index.html"
